version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/quiz-whiz

hooks:
  AfterInstall:
    - location: scripts/build_container.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 10
      runas: root