name: Quiz Whiz CD

on:
  pull_request:
    branches:
      - cd-test
    types: [closed]

jobs:
  deploy:
  
    runs-on: ubuntu-latest

    runs:
      using: 'node16'
      
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: 'us-east-1'
        with:
          aws-region: us-east-1
          aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name quiz-whiz \
            --deployment-group-name QuizWhizEC2 \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}